language: ruby

before_install:
  - gem install bundler

cache:
  directories:
    - bundle

rvm:
  - 2.3.8
  - 2.6.5

script:
    - gem install bundler -v 2.0.2
    - bundle exec rake spec
    - bundle exec danger